version: '3.9'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_DB=admin_finanzas
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - 5050:80
  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: api
    ports:
      - "4000:4000"